[package]
name = "aoc2016"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fancy-regex = "0.10.0"
md5 = "0.7.0"

[profile.dev.package."*"]
opt-level = 3
